#!/bin/bash

pkg_name=${@: -1}

SCRIPT=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")
FFMPEG_DIR="/ffmpeg/FFmpeg-release-4.0"

export PKG_CONFIG_PATH=/ndk/toolchain-android-r10e/lib/pkgconfig:${FFMPEG_DIR}/libswscale:${FFMPEG_DIR}/libswresample:${FFMPEG_DIR}/libpostproc:${FFMPEG_DIR}/libavutil:${FFMPEG_DIR}/libavresample:${FFMPEG_DIR}/libavformat:${FFMPEG_DIR}/libavfilter:${FFMPEG_DIR}/libavdevice:${FFMPEG_DIR}/libavcodec
case $1 in
  --exists)
    pkg-config --exists $pkg_name
    ;;
  --cflags)
    echo $(pkg-config --cflags $pkg_name)
    ;;
  --libs)
    echo $(pkg-config --libs $pkg_name)
    ;;
  *)
    echo "FFmpeg pkg-config to build FFmpeg for Android!"
    ;;
esac
